#!/usr/bin/env bash
# File transfer

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

echo "Transferring file $1 to $3@$2 using key $4"

# Ensure the source file exists
if [ ! -f "$1" ]; then
    echo "Error: Source file $1 does not exist."
    exit 1
fi

# Try to execute the scp command
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
if [ $? -eq 0 ]; then
    echo "File transfer successful!"
else
    echo "File transfer failed."
fi
